In [1]:
import pandas_geojson as pdg

library_geojson = pdg.read_geojson('data/tpl-branch-general-information - 4326.geojson')
library_df = library_geojson.to_dataframe()

library_df

,type,geometry.type,geometry.coordinates,properties._id,properties.BranchCode,properties.PhysicalBranch,properties.BranchName,properties.Address,properties.PostalCode,properties.Website,...,properties.Lat,properties.Long,properties.NBHDNo,properties.NBHDName,properties.TPLNIA,properties.WardNo,properties.WardName,properties.PresentSiteYear,properties.PublicWashroom,properties.Hours
0,Feature,MultiPoint,"[[-79.5845, 43.73999]]",1,AB,1,Albion,"1515 Albion Road, Toronto, ON, M9V 1B2",M9V 1B2,https://www.tpl.ca/albion,...,43.73999,-79.5845,2,Mount Olive-Silverstone-Jamestown,1,1.0,Etobicoke North,1973.0,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....
1,Feature,MultiPoint,"[[-79.26911, 43.70814]]",2,ACD,1,Albert Campbell,"496 Birchmount Road, Toronto, ON, M1K 1N8",M1K 1N8,https://www.tpl.ca/albertcampbell,...,43.70814,-79.26911,120,Clairlea-Birchmount,1,20.0,Scarborough Southwest,1971.0,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....
2,Feature,MultiPoint,"[[-79.54714, 43.60168]]",3,AD,1,Alderwood,"2 Orianna Drive, Toronto, ON, M8W 4Y1",M8W 4Y1,https://www.tpl.ca/alderwood,...,43.60168,-79.54714,20,Alderwood,0,3.0,Etobicoke-Lakeshore,1999.0,NaN,Mon 10 a.m. to 8:30 p.m.; Tue 10 a.m. to 6 p.m...
3,Feature,MultiPoint,"[[-79.29349, 43.78522]]",4,AG,1,Agincourt,"155 Bonis Avenue, Toronto, ON, M1T 3W6",M1T 3W6,https://www.tpl.ca/agincourt,...,43.78522,-79.29349,118,Tam O'Shanter-Sullivan,0,22.0,Scarborough-Agincourt,1991.0,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....
4,Feature,MultiPoint,"[[-79.42178, 43.73922]]",5,AH,1,Armour Heights,"2140 Avenue Road, Toronto, ON, M5M 4M7",M5M 4M7,https://www.tpl.ca/armourheights,...,43.73922,-79.42178,39,Bedford Park-Nortown,0,8.0,Eglinton-Lawrence,1982.0,NaN,Mon 10 a.m. to 8:30 p.m.; Tue 12:30 p.m. to 8:...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Feature,MultiPoint,"[[-79.53836, 43.73977]]",108,WP,1,Woodview Park,"16 Bradstock Road, Toronto, ON, M9M 1M8",M9M 1M8,https://www.tpl.ca/woodview,...,43.73977,-79.53836,22,Humbermede,1,7.0,Humber River-Black Creek,1964.0,1,Mon 10 a.m. to 8:30 p.m.; Tue 12:30 p.m. to 8:...
97,Feature,MultiPoint,"[[-79.27031, 43.8088]]",109,WS,1,Woodside Square,"Woodside Square Mall, 1571 Sandhurst Circle, T...",M1V 1V2,https://www.tpl.ca/woodside,...,43.8088,-79.27031,129,Agincourt North,0,23.0,Scarborough North,1977.0,NaN,Closed
98,Feature,MultiPoint,"[[-79.41755, 43.68222]]",110,WY,1,Wychwood,"1431 Bathurst Street, Toronto, ON, M5R 3J2",M5R 3J2,https://www.tpl.ca/wychwood,...,43.68222,-79.41755,96,Casa Loma,0,12.0,Toronto-St. Paul?s,1916.0,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....
99,Feature,MultiPoint,"[[-79.38864, 43.67192]]",111,YO,1,Yorkville,"22 Yorkville Avenue, Toronto, ON, M4W 1L4",M4W 1L4,https://www.tpl.ca/yorkville,...,43.67192,-79.38864,95,Annex,0,11.0,University-Rosedale,1907.0,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....
100,Feature,MultiPoint,"[[-79.50731, 43.75892]]",112,YW,1,York Woods,"1785 Finch Avenue West, Toronto, ON, M3N 1M6",M3N 1M6,https://www.tpl.ca/yorkwoods,...,43.75892,-79.50731,25,Glenfield-Jane Heights,1,7.0,Humber River-Black Creek,1970.0,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....

In [2]:
# relevant columns

library_columns = [
    'properties.BranchName', 
    'properties.Address', 
    'properties.Website', 
    'properties.SquareFootage', 
    'properties.PublicParking',
    'properties.PublicWashroom',
    'properties.Hours',
    ]

In [3]:
relevant_library_df = library_df[library_columns]

relevant_library_df

,properties.BranchName,properties.Address,properties.Website,properties.SquareFootage,properties.PublicParking,properties.PublicWashroom,properties.Hours
0,Albion,"1515 Albion Road, Toronto, ON, M9V 1B2",https://www.tpl.ca/albion,32279,67,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....
1,Albert Campbell,"496 Birchmount Road, Toronto, ON, M1K 1N8",https://www.tpl.ca/albertcampbell,28957,45,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....
2,Alderwood,"2 Orianna Drive, Toronto, ON, M8W 4Y1",https://www.tpl.ca/alderwood,7341,shared,NaN,Mon 10 a.m. to 8:30 p.m.; Tue 10 a.m. to 6 p.m...
3,Agincourt,"155 Bonis Avenue, Toronto, ON, M1T 3W6",https://www.tpl.ca/agincourt,27690,90,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....
4,Armour Heights,"2140 Avenue Road, Toronto, ON, M5M 4M7",https://www.tpl.ca/armourheights,2988,shared,NaN,Mon 10 a.m. to 8:30 p.m.; Tue 12:30 p.m. to 8:...
...,...,...,...,...,...,...,...
96,Woodview Park,"16 Bradstock Road, Toronto, ON, M9M 1M8",https://www.tpl.ca/woodview,4110,shared,1,Mon 10 a.m. to 8:30 p.m.; Tue 12:30 p.m. to 8:...
97,Woodside Square,"Woodside Square Mall, 1571 Sandhurst Circle, T...",https://www.tpl.ca/woodside,9792,shared,NaN,Closed
98,Wychwood,"1431 Bathurst Street, Toronto, ON, M5R 3J2",https://www.tpl.ca/wychwood,17000,0,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....
99,Yorkville,"22 Yorkville Avenue, Toronto, ON, M4W 1L4",https://www.tpl.ca/yorkville,9053,0,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....
100,York Woods,"1785 Finch Avenue West, Toronto, ON, M3N 1M6",https://www.tpl.ca/yorkwoods,43769,89,1,Mon 9 a.m. to 8:30 p.m.; Tue 9 a.m. to 8:30 p....

In [23]:
for l in relevant_library_df.iterrows():
    print(l[1]['properties.BranchName'])

Albion
Albert Campbell
Alderwood
Agincourt
Armour Heights
Annette Street
Amesbury Park
Brookbanks
Black Creek
Bendale
Beaches
Barbara Frum
Bloor/Gladstone
Brentwood
Bridlewood
Burrows Hall
Cliffcrest
Centennial
Cedarbrae
City Hall
North York Central Library
College/Shaw
Danforth/Coxwell
Daniel G. Hill (formely Jane/Dundas)
Don Mills
Downsview
Deer Park
Dawes Road
Davenport
Dufferin/St. Clair
Eatonville
Elmbrook Park
Evelyn Gregory
Ethennonnhawahstihnen' (formely Bayview)
Eglinton Square
Forest Hill
Fort York
Flemingdon Park
Fairview
Gerrard/Ashdale
Goldhawk Park
Guildwood
Humber Bay
Highland Creek
Hillcrest
High Park
Humber Summit
Humberwood
Jones
Jane/Sheppard
Junction Triangle (formely Perth/Dupont)
Kennedy/Eglinton
Long Branch
Leaside
Locke
Lillian H. Smith
Main Street
Malvern
Maria A. Shchuka
McGregor Park
Mount Dennis
Mimico Centennial
Mount Pleasant
Maryvale
Morningside
Northern District
Northern Elms
New Toronto
Oakwood Village Library and Arts Centre
Pape/Danforth
Parkdale
Parliament Street
Palmerston
Port Union
Pleasant View
Queen/Saulter
Riverdale
Richview
Runnymede
Rexdale
Sanderson
Sunnybrook Hospital
Scarborough Civic Centre
St. Clair/Silverthorn
St. James Town
St. Lawrence
Spadina Road
Steeles
Swansea Memorial
S. Walter Stewart
Taylor Memorial
Thorncliffe
Todmorden Room
Toronto Reference Library
Victoria Village
Weston
Woodview Park
Woodside Square
Wychwood
Yorkville
York Woods